#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){

	short highest, lowest, threshold, color;

	highest = lowest = getColorReflected(S3);

	while(1){

		color = getColorReflected(S3);

		if(color < lowest){

			lowest = color;

		}

		if(color > highest){

			highest = color;

		}

		threshold = (highest - lowest) / 2;

		displayString(1, "Current value is %d", color);
		displayString(2, "Highest is %d", highest);
		displayString(3, "Lowest is %d", lowest);
		displayString(4, "I am on %s", color > threshold ? "white" : "black");

		sleep(20);



	}


}
