#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void moveRobot(long nMotorRatio, long time, long power){

	setMotorSyncTime(rightMotor, leftMotor, nMotorRatio, time, power);
	sleep(time);

}

task main(){

	/* A: */

	// 4 times to go in a square
	for(int i = 0; i < 4; i++){

		// Go forward
		moveRobot(0, 1000, 30);


		// Turn right
		moveRobot(100, 600, 30);

	}

	/* B: */

	// Spin left or right randomly
	if(random(1)){
			moveRobot(100, 2400, 30);
	} else {
			moveRobot(-100, 2400, 30);
	}



	/* C: */

	// Forward full speed 5 seconds
	moveRobot(0, 5000, 100);

	// Turn 180
	moveRobot(100, 1200, 30);

	// Forward at half speed
	moveRobot(0, 7250, 50);

}
