#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void drive(long nMotorRatio, long dist, long power){

	long centimetres = 20.4627783975294 * dist;

	setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, centimetres, power);

}

void turn90(long nMotorRatio, long power){

	setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, 360, power);

}

task main(){

	// Decide on left or right
	int direction = random(1);
	int i;


	// Square 240cm perimeter
	for(i = 0;i<4;i++){

		// Forward 60 cms
		drive(0, 60, 50);
		waitUntilMotorStop(leftMotor);

		// Turn left or right depending on random
		if(direction){

			turn90(50, 50);
			waitUntilMotorStop(leftMotor);

		} else {

			turn90(-50, 50);
			waitUntilMotorStop(leftMotor);

		}

	}

	// Forward 100cm at 100%
	drive(0, 100, 100);
	waitUntilMotorStop(leftMotor);

	// Spin 180
	if(direction){

		turn90(50, 50);
		waitUntilMotorStop(leftMotor);
		turn90(50, 50);
		waitUntilMotorStop(leftMotor);

	} else {

		turn90(-50, 50);
		waitUntilMotorStop(leftMotor);
		turn90(-50, 50);
		waitUntilMotorStop(leftMotor);

	}

	// Return to original at 25%
	drive(0, 100, 25);
	waitUntilMotorStop(leftMotor);


}
